# Generated by Django 4.2.23 on 2025-08-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
