# Generated by Django 4.2.23 on 2025-08-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
