# Generated by Django 4.2.23 on 2025-08-05 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_post_content_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='writer',
        ),
    ]
