# Generated by Django 4.2.23 on 2025-08-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
